1、获取板块数据
2、获取板块成分股数据
3、分析板块量价
4、分析锚定个股追寻何种板块
5、分析锚定个股追寻板块弄一个龙头股

In [ ]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2026/2/24 10:16
# @Author : chenyanwen
# @email:1183445504@qq.com
import time
import akshare as ak
import pandas as pd
import numpy as np
import tqdm
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from sqlalchemy import create_engine
from datetime import datetime
from dateutil.relativedelta import relativedelta
import pymysql
import logging

# ==============================
# 日志配置
# ==============================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# ==============================
# 日期范围
# ==============================
today = datetime.today().replace(hour=0, minute=0, second=0, microsecond=0)
one_year_ago = today - relativedelta(years=1)

start_date = one_year_ago.strftime("%Y%m%d")
end_date = today.strftime("%Y%m%d")

logger.info(f"当前日期：{end_date}")
logger.info(f"近一年起始日期：{start_date}")

# ==============================
# 数据库连接
# ==============================
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")

conn = pymysql.connect(
    host='127.0.0.1',
    user='root',
    password='chen',
    database='gp',
    autocommit=False
)
cursor = conn.cursor()

c:\Users\cyw\.conda\envs\stock\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
C:\Users\cyw\AppData\Roaming\Python\Python310\site-packages\py_mini_racer\py_mini_racer.py:15: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-03-20 10:27:34 [INFO] 当前日期：20260320
2026-03-20 10:27:34 [INFO] 近一年起始日期：20250320

In [30]:
analy_sql="""select * from gp.stock_analysis where need_to_analysis=1"""
analy_df=pd.read_sql(sql=analy_sql,con=engine)

In [ ]:
analy_df['code2']=analy_df['stock_code'].map(lambda x:x[2:])

In [ ]:
analy_df['code2']=analy_df['code2'].astype(str)

In [33]:
block_relx_sql=f"""select * from gp.tdx_block_stocks where block_type='概念板块'"""
block_relx_df=pd.read_sql(sql=block_relx_sql,con=engine)

In [34]:
block_detail_sql=f"""select * from gp.tdx_block_daily where create_date='2026-03-19'"""
block_detail_df=pd.read_sql(sql=block_detail_sql,con=engine)

In [36]:
# Z-score（相对市场）
mean = block_detail_df['strength'].mean()
std = block_detail_df['strength'].std()

block_detail_df['zscore'] = (block_detail_df['strength'] - mean) / std

In [40]:
block_detail_df['norm_score'] = 1 / (1 + np.exp(-block_detail_df['zscore']))

In [42]:
block_detail_df[['code','name','strength','zscore','norm_score']]

       code  name  strength    zscore  norm_score
0    880201   黑龙江      1.11  1.716306    0.847652
1    880202  新疆板块      0.64  1.299459    0.785744
2    880203  吉林板块     -1.00 -0.155074    0.461309
3    880204  甘肃板块     -2.00 -1.041985    0.260767
4    880205  辽宁板块     -1.47 -0.571922    0.360793
..      ...   ...       ...       ...         ...
554  881468    水务      0.17  0.882611    0.707363
555  881470  环保设备     -1.32 -0.438886    0.392007
556  881471  环境治理     -0.21  0.545585    0.633111
557  881476  环境监测     -1.36 -0.474362    0.383584
558  881478   综合类     -1.88 -0.935556    0.281799

[559 rows x 5 columns]

In [46]:
# 市场因子：>0.5 偏强，<0.5 偏弱
market_mean = block_detail_df['norm_score'].mean()
# 市场因子：>0.5 偏强，<0.5 偏弱
market_factor = (market_mean - 0.5) * 2   # 映射到 [-1,1]

print("\n市场环境因子:", round(market_factor, 4))

市场环境因子: -0.0085

In [47]:
# =============================
# 5️⃣ 共振模型（完整版本🔥）
# =============================
def calc_resonance(scores, market_factor):

    scores = np.array(scores)

    # 过滤无效
    if len(scores) == 0:
        return 0

    # 1️⃣ 强度
    strength = scores.mean()

    # 2️⃣ 一致性（防分化）
    consistency = 1 / (1 + scores.std())

    # 3️⃣ 强者放大
    power = np.mean(scores ** 2)

    # 4️⃣ 数量因子（递减）
    count_bonus = np.log(len(scores) + 1)

    # 5️⃣ 综合
    base_score = 0.4 * strength + 0.3 * consistency + 0.3 * power

    # 6️⃣ 市场环境修正
    final_score = base_score * (1 + market_factor)

    return final_score

In [ ]:
analy_df

,stock_code,stock_name,need_to_analysis,trigger_count,industry_block,concept_block,region_block,concept_block_resonance,create_time,update_time,code2
0,sz000617,中油资本,1,1,多元金融(强度:3.01),数字货币(强度:0.07)|跨境支付CIPS(强度:0.02)|中特估(强度:0.01),新疆板块(强度:0.64),None,2026-03-19 17:32:28,2026-03-19 17:32:28,000617
1,sz002432,九安医疗,1,1,医疗器械(强度:-0.62),智能医疗(强度:-0.41)|创投概念(强度:-0.7)|新零售(强度:-0.81),天津板块(强度:-0.69),None,2026-03-19 17:32:28,2026-03-19 17:32:28,002432

In [53]:
analy_stock_block_relx=pd.merge(left=analy_df,right=block_relx_df,left_on='code2',right_on='stock_code',how='left')

In [55]:
analy_stock_block_relx.head(1)

,stock_code_x,stock_name_x,need_to_analysis,trigger_count,industry_block,concept_block,region_block,concept_block_resonance,create_time,update_time,code2,block_code,block_name,stock_code_y,stock_name_y,block_type,created_at
0,sz000617,中油资本,1,1,多元金融(强度:3.01),数字货币(强度:0.07)|跨境支付CIPS(强度:0.02)|中特估(强度:0.01),新疆板块(强度:0.64),None,2026-03-19 17:32:28,2026-03-19 17:32:28,000617,880519,碳中和,000617,中油资本,概念板块,2026-03-18 14:25:35

In [56]:
results = []

for stock, blocks in analy_stock_block_relx.groupby('stock_code_x'):
    block_one_detail=block_detail_df.loc[block_detail_df['code'].isin(blocks['block_code'].to_list())]
    scores = block_one_detail['norm_score']

    resonance_score = calc_resonance(scores, market_factor)

    results.append({
        'stock': stock,
        'resonance_score': resonance_score
    })

df_result = pd.DataFrame(results)

# 排序
df_result = df_result.sort_values('resonance_score', ascending=False)

print("\n=== 股票共振强度排名 ===")
print(df_result)

=== 股票共振强度排名 ===
      stock  resonance_score
0  sz000617         0.607362
1  sz002432         0.529822

In [58]:
analy_df=pd.merge(left=analy_df,right=df_result,left_on='stock_code',right_on='stock',how='left')

In [60]:
analy_df.columns

Index(['stock_code', 'stock_name', 'need_to_analysis', 'trigger_count',
       'industry_block', 'concept_block', 'region_block',
       'concept_block_resonance', 'create_time', 'update_time', 'code2',
       'stock', 'resonance_score'],
      dtype='object')

In [63]:
analy_df=analy_df[['stock_code', 'stock_name', 'need_to_analysis', 'trigger_count',
       'industry_block', 'concept_block', 'region_block',
        'create_time', 'update_time', 'resonance_score']]
analy_df=analy_df.rename(columns={'resonance_score':'concept_block_resonance'})

In [ ]:
def get_best_block(x,trade_date=None):
    stock_code = x['stock_code'][2:]
    if trade_date:
        trade_date = x['trade_date']
    sql = f"""
        select * from gp.tdx_block_daily as datail
        join (
            select block_code, block_name, block_type
            from gp.tdx_block_stocks as rlx
            where rlx.stock_code = '{stock_code}'
        ) as rlx 
        on datail.code = rlx.block_code
        where datail.create_date = '{trade_date}'
    """
    block_detail_df = pd.read_sql(sql=sql, con=engine)
    block_detail_df = block_detail_df.loc[
        block_detail_df['block_type'].isin(['地区板块', '概念板块', '行业板块'])
    ]

    block_dq_df = block_detail_df.loc[block_detail_df['block_type']=='地区板块'].sort_values('strength', ascending=False).reset_index(drop=True)
    block_hy_df = block_detail_df.loc[block_detail_df['block_type']=='行业板块'].sort_values('strength', ascending=False).reset_index(drop=True)
    block_gn_df = block_detail_df.loc[block_detail_df['block_type']=='概念板块'].sort_values('strength', ascending=False).reset_index(drop=True)
    # print(stock_code,trade_date,block_detail_df)
    # 如果为空，返回空字符串
    top_2_gn=block_gn_df.loc[0:2]
    gn_list = [f"{row['name']}(强度:{row['strength']})" for _, row in top_2_gn.iterrows()]
    
    # 用 "|" 拼接
    gn = "|".join(gn_list)
    dq = f"{block_dq_df.loc[0,'name']}(强度:{block_dq_df.loc[0,'strength']})" if not block_dq_df.empty else ""
    hy = f"{block_hy_df.loc[0,'name']}(强度:{block_hy_df.loc[0,'strength']})" if not block_hy_df.empty else ""
    
    return dq, hy, gn

,stock_code,stock_name,need_to_analysis,trigger_count,industry_block,concept_block,region_block,create_time,update_time,concept_block_resonance
0,sz000617,中油资本,1,1,多元金融(强度:3.01),数字货币(强度:0.07)|跨境支付CIPS(强度:0.02)|中特估(强度:0.01),新疆板块(强度:0.64),2026-03-19 17:32:28,2026-03-19 17:32:28,0.607362
1,sz002432,九安医疗,1,1,医疗器械(强度:-0.62),智能医疗(强度:-0.41)|创投概念(强度:-0.7)|新零售(强度:-0.81),天津板块(强度:-0.69),2026-03-19 17:32:28,2026-03-19 17:32:28,0.529822

In [67]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2026/2/24 10:16
# @Author : chenyanwen
# @email:1183445504@qq.com
import time
import akshare as ak
import pandas as pd
import numpy as np
import tqdm
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from sqlalchemy import create_engine
from datetime import datetime
from dateutil.relativedelta import relativedelta
import pymysql
import logging

# ==============================
# 日志配置
# ==============================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# ==============================
# 日期范围
# ==============================
today = datetime.today().replace(hour=0, minute=0, second=0, microsecond=0)
one_year_ago = today - relativedelta(years=1)

start_date = one_year_ago.strftime("%Y%m%d")
end_date = today.strftime("%Y%m%d")

logger.info(f"当前日期：{end_date}")
logger.info(f"近一年起始日期：{start_date}")

# ==============================
# 数据库连接
# ==============================
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")

conn = pymysql.connect(
    host='127.0.0.1',
    user='root',
    password='chen',
    database='gp',
    autocommit=False
)
cursor = conn.cursor()



# =============================
# 5️⃣ 共振模型（完整版本🔥）
# =============================
def calc_resonance(scores, market_factor):

    scores = np.array(scores)

    # 过滤无效
    if len(scores) == 0:
        return 0

    # 1️⃣ 强度
    strength = scores.mean()

    # 2️⃣ 一致性（防分化）
    consistency = 1 / (1 + scores.std())

    # 3️⃣ 强者放大
    power = np.mean(scores ** 2)

    # 4️⃣ 数量因子（递减）
    count_bonus = np.log(len(scores) + 1)

    # 5️⃣ 综合
    base_score = 0.4 * strength + 0.3 * consistency + 0.3 * power

    # 6️⃣ 市场环境修正
    final_score = base_score * (1 + market_factor)

    return final_score



analy_sql="""select * from gp.stock_analysis where need_to_analysis=1"""
analy_df=pd.read_sql(sql=analy_sql,con=engine)
analy_df['code2']=analy_df['stock_code'].map(lambda x:x[2:])
analy_df['code2']=analy_df['code2'].astype(str)


block_relx_sql=f"""select * from gp.tdx_block_stocks"""
block_relx_df=pd.read_sql(sql=block_relx_sql,con=engine)

# where block_type='概念板块
block_relx_concept_df=block_relx_df.loc[block_relx_df['block_type']=='概念板块']



block_detail_sql=f"""select * from gp.tdx_block_daily where create_date='2026-03-19'"""
block_detail_df=pd.read_sql(sql=block_detail_sql,con=engine)


# Z-score（相对市场）
mean = block_detail_df['strength'].mean()
std = block_detail_df['strength'].std()

block_detail_df['zscore'] = (block_detail_df['strength'] - mean) / std


block_detail_df['norm_score'] = 1 / (1 + np.exp(-block_detail_df['zscore']))


# 市场因子：>0.5 偏强，<0.5 偏弱
market_mean = block_detail_df['norm_score'].mean()
# 市场因子：>0.5 偏强，<0.5 偏弱
market_factor = (market_mean - 0.5) * 2   # 映射到 [-1,1]

print("\n市场环境因子:", round(market_factor, 4))

analy_stock_concept_block_relx=pd.merge(left=analy_df,right=block_relx_concept_df,left_on='code2',right_on='stock_code',how='left')


results = []

for stock, blocks in analy_stock_concept_block_relx.groupby('stock_code_x'):
    block_one_detail=block_detail_df.loc[block_detail_df['code'].isin(blocks['block_code'].to_list())]
    scores = block_one_detail['norm_score']

    resonance_score = calc_resonance(scores, market_factor)

    results.append({
        'stock': stock,
        'resonance_score': resonance_score
    })

df_result = pd.DataFrame(results)

# 排序
df_result = df_result.sort_values('resonance_score', ascending=False)

print("\n=== 股票共振强度排名 ===")
print(df_result)


analy_df=pd.merge(left=analy_df,right=df_result,left_on='stock_code',right_on='stock',how='left')


# analy_df=analy_df[['stock_code', 'stock_name', 'need_to_analysis', 'trigger_count',
#        'industry_block', 'concept_block', 'region_block',
#         'create_time', 'update_time', 'resonance_score']]
# analy_df=analy_df.rename(columns={'resonance_score':'concept_block_resonance'})

2026-03-20 11:32:22 [INFO] 当前日期：20260320
2026-03-20 11:32:22 [INFO] 近一年起始日期：20250320

市场环境因子: -0.0085

=== 股票共振强度排名 ===
      stock  resonance_score
0  sz000617         0.607362
1  sz002432         0.529822

In [87]:
def get_top3_block(x,trade_date=None):
    stock_code=x['stock_code']
    # print(1)
    analy_stock_block_dq_filter=analy_stock_block_relx.loc[(analy_stock_block_relx['stock_code_x']==stock_code)&(analy_stock_block_relx['block_type']=='地区板块')]
    block_detail_one_dq_df = block_detail_df.loc[block_detail_df['code'].isin(analy_stock_block_dq_filter['block_code'].to_list())].sort_values('strength', ascending=False).reset_index(drop=True)
    # print(1)
    analy_stock_block_gn_filter=analy_stock_block_relx.loc[(analy_stock_block_relx['stock_code_x']==stock_code)&(analy_stock_block_relx['block_type']=='概念板块')]
    block_detail_one_gn_df = block_detail_df.loc[block_detail_df['code'].isin(analy_stock_block_gn_filter['block_code'].to_list())].sort_values('strength', ascending=False).reset_index(drop=True)
    # print(1)
    analy_stock_block_hy_filter=analy_stock_block_relx.loc[(analy_stock_block_relx['stock_code_x']==stock_code)&(analy_stock_block_relx['block_type']=='行业板块')]
    block_detail_one_hy_df = block_detail_df.loc[block_detail_df['code'].isin(analy_stock_block_hy_filter['block_code'].to_list())].sort_values('strength', ascending=False).reset_index(drop=True)
    # print(1)




    top_2_gn=block_detail_one_gn_df.loc[0:2]
    gn_list = [f"{row['name']}(强度:{row['strength']})" for _, row in top_2_gn.iterrows()]
    
    # 用 "|" 拼接
    gn = "，".join(gn_list)
    dq = f"{block_detail_one_dq_df.loc[0,'name']}(强度:{block_detail_one_dq_df.loc[0,'strength']})" if not block_detail_one_dq_df.empty else ""
    hy = f"{block_detail_one_hy_df.loc[0,'name']}(强度:{block_detail_one_hy_df.loc[0,'strength']})" if not block_detail_one_hy_df.empty else ""
    
    return dq, hy, gn

In [68]:
analy_stock_block_relx=pd.merge(left=analy_df,right=block_relx_df,left_on='code2',right_on='stock_code',how='left')

In [88]:
analy_df[['region_block1','industry_block1','concept_block1']]=analy_df.apply(get_top3_block, axis=1, result_type='expand',args=(None))

In [89]:
analy_df.head()

,stock_code,stock_name,need_to_analysis,trigger_count,industry_block,concept_block,region_block,concept_block_resonance,create_time,update_time,code2,stock,resonance_score,region_block1,industry_block1,concept_block1
0,sz000617,中油资本,1,1,多元金融(强度:3.01),数字货币(强度:0.07)|跨境支付CIPS(强度:0.02)|中特估(强度:0.01),新疆板块(强度:0.64),None,2026-03-19 17:32:28,2026-03-19 17:32:28,000617,sz000617,0.607362,新疆板块(强度:0.64),多元金融(强度:3.01),数字货币(强度:0.07)，跨境支付CIPS(强度:0.02)，中特估(强度:0.01)
1,sz002432,九安医疗,1,1,医疗器械(强度:-0.62),智能医疗(强度:-0.41)|创投概念(强度:-0.7)|新零售(强度:-0.81),天津板块(强度:-0.69),None,2026-03-19 17:32:28,2026-03-19 17:32:28,002432,sz002432,0.529822,天津板块(强度:-0.69),医疗器械(强度:-0.62),智能医疗(强度:-0.41)，创投概念(强度:-0.7)，新零售(强度:-0.81)