1、获取板块数据
2、获取板块成分股数据
3、分析板块量价
4、分析锚定个股追寻何种板块
5、分析锚定个股追寻板块弄一个龙头股

In [2]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2026/2/24 10:16
# @Author : chenyanwen
# @email:1183445504@qq.com
import time
import akshare as ak
import pandas as pd
import numpy as np
import tqdm
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from sqlalchemy import create_engine
from datetime import datetime
from dateutil.relativedelta import relativedelta
import pymysql
import logging

# ==============================
# 日志配置
# ==============================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# ==============================
# 日期范围
# ==============================
today = datetime.today().replace(hour=0, minute=0, second=0, microsecond=0)
one_year_ago = today - relativedelta(years=1)

start_date = one_year_ago.strftime("%Y%m%d")
end_date = today.strftime("%Y%m%d")

logger.info(f"当前日期：{end_date}")
logger.info(f"近一年起始日期：{start_date}")

# ==============================
# 数据库连接
# ==============================
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")

conn = pymysql.connect(
    host='127.0.0.1',
    user='root',
    password='chen',
    database='gp',
    autocommit=False
)

cursor = conn.cursor()

2026-02-26 17:31:59 [INFO] 当前日期：20260226
2026-02-26 17:31:59 [INFO] 近一年起始日期：20250226

In [ ]:
stock_board_concept_name_em_df = ak.stock_board_concept_name_em()

  0%|          | 0/4 [00:00<?, ?it/s]

In [8]:
stock_board_concept_name_em_df.head()

,排名,板块名称,板块代码,最新价,涨跌额,涨跌幅,总市值,换手率,上涨家数,下跌家数,领涨股票,领涨股票-涨跌幅
0,1,地热能,BK0622,6008.86,251.60,4.37,112093715000,5.01,7,1,豫能控股,9.97
1,2,CPO概念,BK1128,6275.84,256.27,4.26,3197434592000,6.35,38,4,杰普特,20.00
2,3,铜缆高速连接,BK1168,2717.62,90.78,3.46,1092564192000,3.94,33,4,中天科技,10.01
3,4,光通信模块,BK1136,3019.58,100.62,3.45,3401528976000,6.18,65,9,云南锗业,10.01
4,5,PCB,BK0877,3363.77,105.81,3.25,3518617680000,5.27,108,20,贤丰控股,10.00

In [4]:
stock_board_concept_hist_em_df = ak.stock_board_concept_hist_em(symbol="绿色电力", period="daily", start_date="20260101", end_date="20260226", adjust="")
stock_board_concept_hist_em_df.head()

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [ ]:
def fetch_stock_data(row, retry=3):
    symbol = row['板块代码']
    name = row['板块名称']

    for i in range(retry):
        try:
            df = ak.stock_board_concept_hist_em(
                symbol=name,
                start_date=start_date,
                end_date=end_date,
                adjust="qfq"
            )

            if df is None or df.empty:
                return None

            df['code'] = symbol
            df['name'] = name

            logger.info(f"完成: {symbol}")
            return df

        except Exception as e:
            logger.warning(f"{symbol} 第{i+1}次失败: {e}")
            time.sleep(1)

    logger.error(f"{symbol} 获取失败")
    return None

,排名,板块名称,板块代码,最新价,涨跌额,涨跌幅,总市值,换手率,上涨家数,下跌家数,领涨股票,领涨股票-涨跌幅
0,1,地热能,BK0622,6008.86,251.60,4.37,112093715000,5.01,7,1,豫能控股,9.97
1,2,CPO概念,BK1128,6275.84,256.27,4.26,3197434592000,6.35,38,4,杰普特,20.00
2,3,铜缆高速连接,BK1168,2717.62,90.78,3.46,1092564192000,3.94,33,4,中天科技,10.01
3,4,光通信模块,BK1136,3019.58,100.62,3.45,3401528976000,6.18,65,9,云南锗业,10.01
4,5,PCB,BK0877,3363.77,105.81,3.25,3518617680000,5.27,108,20,贤丰控股,10.00