In [1]:
import logging

import numpy as np
import pandas as pd
import akshare as ak

import warnings
warnings.filterwarnings("ignore", category=UserWarning)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

In [2]:
df = ak.stock_zh_a_tick_tx_js(symbol='sz002487')

In [14]:
df.to_excel('1.xlsx')

In [3]:
df.head()

       成交时间   成交价格  价格变动   成交量     成交金额  性质
0  09:25:00  70.36  0.46  1315  9252340  买盘
1  09:30:00  70.50  0.14   834  5871373  买盘
2  09:30:03  70.48 -0.02   374  2638263  卖盘
3  09:30:06  70.42 -0.06   652  4590780  卖盘
4  09:30:09  70.37 -0.05   264  1858127  卖盘

In [22]:
# ===== 1️⃣ 转时间格式 =====
df["成交时间"] = pd.to_datetime(df["成交时间"])

# ===== 2️⃣ 提取分钟 =====
df["分钟"] = df["成交时间"].dt.floor("min")

# ===== 3️⃣ 标记买卖 =====
df["买量"] = df.apply(lambda x: x["成交量"] if x["性质"] == "买盘" or (x["性质"]=="中性盘" and x["价格变动"]>0) else 0, axis=1)

df["卖量"] = df.apply(lambda x: x["成交量"] if x["性质"] == "卖盘" or (x["性质"]=="中性盘" and x["价格变动"]<0) else 0, axis=1)

# ===== 4️⃣ 按分钟聚合 =====
minute_df = df.groupby("分钟").agg({
    "买量": "sum",
    "卖量": "sum",
    "成交量": "sum"
}).reset_index()

# ===== 5️⃣ 计算买卖比 =====
minute_df["买卖比"] = minute_df["买量"] / (minute_df["卖量"] + 1e-6)
minute_df["买卖差"] = minute_df["买量"] - minute_df["卖量"]
minute_df["买卖比"] = minute_df["买卖比"].round(2)
minute_df["买卖比"] = minute_df["买卖比"].map(lambda x: f"{x:.2f}")
print(minute_df)

                     分钟    买量    卖量   成交量            买卖比   买卖差
0   2026-03-22 09:25:00  1315     0  1315  1315000000.00  1315
1   2026-03-22 09:30:00  3166  3218  6569           0.98   -52
2   2026-03-22 09:31:00  2424   774  3198           3.13  1650
3   2026-03-22 09:32:00  1556  1435  2991           1.08   121
4   2026-03-22 09:33:00  1069  1728  2797           0.62  -659
..                  ...   ...   ...   ...            ...   ...
236 2026-03-22 14:54:00   388  1050  1438           0.37  -662
237 2026-03-22 14:55:00  1304   916  2220           1.42   388
238 2026-03-22 14:56:00  1184  1671  2855           0.71  -487
239 2026-03-22 14:57:00    58     0    58    58000000.00    58
240 2026-03-22 15:00:00     0  3583  3583           0.00 -3583

[241 rows x 6 columns]

In [23]:
minute_df["order_flow"] = (
    minute_df["买量"] - minute_df["卖量"]
) / (minute_df["成交量"] + 1e-6)

In [24]:
minute_df["买占比"] = minute_df["买量"] / (minute_df["成交量"] + 1e-6)

In [25]:
minute_df.head(20)

,分钟,买量,卖量,成交量,买卖比,买卖差,order_flow,买占比
0,2026-03-22 09:25:00,1315,0,1315,1315000000.00,1315,1.000000,1.000000
1,2026-03-22 09:30:00,3166,3218,6569,0.98,-52,-0.007916,0.481961
2,2026-03-22 09:31:00,2424,774,3198,3.13,1650,0.515947,0.757974
3,2026-03-22 09:32:00,1556,1435,2991,1.08,121,0.040455,0.520227
4,2026-03-22 09:33:00,1069,1728,2797,0.62,-659,-0.235610,0.382195
5,2026-03-22 09:34:00,323,2004,2327,0.16,-1681,-0.722389,0.138805
6,2026-03-22 09:35:00,1579,1169,2774,1.35,410,0.147801,0.569214
7,2026-03-22 09:36:00,2207,654,2861,3.37,1553,0.542817,0.771409
8,2026-03-22 09:37:00,5116,1384,6500,3.70,3732,0.574154,0.787077
9,2026-03-22 09:38:00,2344,2155,4499,1.09,189,0.042009,0.521005
10,2026-03-22 09:39:00,3878,1598,5476,2.43,2280,0.416362,0.708181
11,2026-03-22 09:40:00,1619,2420,4039,0.67,-801,-0.198316,0.400842
12,2026-03-22 09:41:00,3692,1669,5361,2.21,2023,0.377355,0.688677
13,2026-03-22 09:42:00,2393,1365,3758,1.75,1028,0.273550,0.636775
14,2026-03-22 09:43:00,1439,1451,2890,0.99,-12,-0.004152,0.497924
15,2026-03-22 09:44:00,3903,1033,4936,3.78,2870,0.581442,0.790721
16,2026-03-22 09:45:00,3189,2419,5867,1.32,770,0.131243,0.543549
17,2026-03-22 09:46:00,1089,2016,3105,0.54,-927,-0.298551,0.350725
18,2026-03-22 09:47:00,562,1337,1899,0.42,-775,-0.408110,0.295945
19,2026-03-22 09:48:00,1057,2353,3410,0.45,-1296,-0.380059,0.309971

In [28]:
df["累计成交额"] = df["成交金额"].cumsum()
df["累计成交量"] = df["成交量"].cumsum()*100
df["VWAP"] = df["累计成交额"] / df["累计成交量"]

In [30]:
df.head(20)

,成交时间,成交价格,价格变动,成交量,成交金额,性质,分钟,买量,卖量,累计成交额,累计成交量,VWAP
0,2026-03-22 09:25:00,70.36,0.46,1315,9252340,买盘,2026-03-22 09:25:00,1315,0,9252340,131500,70.360000
1,2026-03-22 09:30:00,70.50,0.14,834,5871373,买盘,2026-03-22 09:30:00,834,0,15123713,214900,70.375584
2,2026-03-22 09:30:03,70.48,-0.02,374,2638263,卖盘,2026-03-22 09:30:00,0,374,17761976,252300,70.400222
3,2026-03-22 09:30:06,70.42,-0.06,652,4590780,卖盘,2026-03-22 09:30:00,0,652,22352756,317500,70.402381
4,2026-03-22 09:30:09,70.37,-0.05,264,1858127,卖盘,2026-03-22 09:30:00,0,264,24210883,343900,70.400939
5,2026-03-22 09:30:12,70.36,-0.01,518,3645070,卖盘,2026-03-22 09:30:00,0,518,27855953,395700,70.396646
6,2026-03-22 09:30:15,70.32,-0.04,185,1301441,卖盘,2026-03-22 09:30:00,0,185,29157394,414200,70.394481
7,2026-03-22 09:30:18,70.25,-0.07,80,562356,卖盘,2026-03-22 09:30:00,0,80,29719750,422200,70.392586
8,2026-03-22 09:30:21,70.13,-0.12,65,456086,卖盘,2026-03-22 09:30:00,0,65,30175836,428700,70.389167
9,2026-03-22 09:30:24,70.00,-0.13,151,1057270,卖盘,2026-03-22 09:30:00,0,151,31233106,443800,70.376534
10,2026-03-22 09:30:27,69.88,-0.12,53,370587,卖盘,2026-03-22 09:30:00,0,53,31603693,449100,70.371171
11,2026-03-22 09:30:30,69.88,0.00,301,2103432,卖盘,2026-03-22 09:30:00,0,301,33707125,479200,70.340411
12,2026-03-22 09:30:33,69.80,-0.08,78,544576,卖盘,2026-03-22 09:30:00,0,78,34251701,487000,70.332035
13,2026-03-22 09:30:36,69.61,-0.19,312,2176966,卖盘,2026-03-22 09:30:00,0,312,36428667,518200,70.298470
14,2026-03-22 09:30:39,69.60,-0.01,185,1287968,卖盘,2026-03-22 09:30:00,0,185,37716635,536700,70.275079
15,2026-03-22 09:30:42,69.61,0.01,597,4155021,买盘,2026-03-22 09:30:00,597,0,41871656,596400,70.207337
16,2026-03-22 09:30:45,69.81,0.20,791,5517315,买盘,2026-03-22 09:30:00,791,0,47388971,675500,70.153917
17,2026-03-22 09:30:48,70.00,0.19,465,3246744,买盘,2026-03-22 09:30:00,465,0,50635715,722000,70.132569
18,2026-03-22 09:30:51,70.11,0.11,97,679067,买盘,2026-03-22 09:30:00,97,0,51314782,731700,70.130903
19,2026-03-22 09:30:54,70.36,0.25,382,2682684,买盘,2026-03-22 09:30:00,382,0,53997466,769900,70.135688

In [31]:
df["VWAP斜率"] = df["VWAP"].diff()
df["均价抬高"] = df["VWAP斜率"] > 0

In [32]:
df.head(20)

,成交时间,成交价格,价格变动,成交量,成交金额,性质,分钟,买量,卖量,累计成交额,累计成交量,VWAP,VWAP斜率,均价抬高
0,2026-03-22 09:25:00,70.36,0.46,1315,9252340,买盘,2026-03-22 09:25:00,1315,0,9252340,131500,70.360000,NaN,False
1,2026-03-22 09:30:00,70.50,0.14,834,5871373,买盘,2026-03-22 09:30:00,834,0,15123713,214900,70.375584,0.015584,True
2,2026-03-22 09:30:03,70.48,-0.02,374,2638263,卖盘,2026-03-22 09:30:00,0,374,17761976,252300,70.400222,0.024638,True
3,2026-03-22 09:30:06,70.42,-0.06,652,4590780,卖盘,2026-03-22 09:30:00,0,652,22352756,317500,70.402381,0.002159,True
4,2026-03-22 09:30:09,70.37,-0.05,264,1858127,卖盘,2026-03-22 09:30:00,0,264,24210883,343900,70.400939,-0.001442,False
5,2026-03-22 09:30:12,70.36,-0.01,518,3645070,卖盘,2026-03-22 09:30:00,0,518,27855953,395700,70.396646,-0.004293,False
6,2026-03-22 09:30:15,70.32,-0.04,185,1301441,卖盘,2026-03-22 09:30:00,0,185,29157394,414200,70.394481,-0.002166,False
7,2026-03-22 09:30:18,70.25,-0.07,80,562356,卖盘,2026-03-22 09:30:00,0,80,29719750,422200,70.392586,-0.001894,False
8,2026-03-22 09:30:21,70.13,-0.12,65,456086,卖盘,2026-03-22 09:30:00,0,65,30175836,428700,70.389167,-0.003419,False
9,2026-03-22 09:30:24,70.00,-0.13,151,1057270,卖盘,2026-03-22 09:30:00,0,151,31233106,443800,70.376534,-0.012633,False
10,2026-03-22 09:30:27,69.88,-0.12,53,370587,卖盘,2026-03-22 09:30:00,0,53,31603693,449100,70.371171,-0.005363,False
11,2026-03-22 09:30:30,69.88,0.00,301,2103432,卖盘,2026-03-22 09:30:00,0,301,33707125,479200,70.340411,-0.030760,False
12,2026-03-22 09:30:33,69.80,-0.08,78,544576,卖盘,2026-03-22 09:30:00,0,78,34251701,487000,70.332035,-0.008376,False
13,2026-03-22 09:30:36,69.61,-0.19,312,2176966,卖盘,2026-03-22 09:30:00,0,312,36428667,518200,70.298470,-0.033565,False
14,2026-03-22 09:30:39,69.60,-0.01,185,1287968,卖盘,2026-03-22 09:30:00,0,185,37716635,536700,70.275079,-0.023391,False
15,2026-03-22 09:30:42,69.61,0.01,597,4155021,买盘,2026-03-22 09:30:00,597,0,41871656,596400,70.207337,-0.067742,False
16,2026-03-22 09:30:45,69.81,0.20,791,5517315,买盘,2026-03-22 09:30:00,791,0,47388971,675500,70.153917,-0.053420,False
17,2026-03-22 09:30:48,70.00,0.19,465,3246744,买盘,2026-03-22 09:30:00,465,0,50635715,722000,70.132569,-0.021348,False
18,2026-03-22 09:30:51,70.11,0.11,97,679067,买盘,2026-03-22 09:30:00,97,0,51314782,731700,70.130903,-0.001666,False
19,2026-03-22 09:30:54,70.36,0.25,382,2682684,买盘,2026-03-22 09:30:00,382,0,53997466,769900,70.135688,0.004784,True

In [ ]:

import baostock as bs
import pandas as pd
import tqdm
#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

#### 获取沪深A股历史K线数据 ####
# 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
# 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
# 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
stock_list=[
"sh.600370",
"sz.002310",
"sh.601669",
"sh.601858",
"sh.601868",
"sh.600522",
"sh.603929",
"sh.603558",
"sz.000536",
"sh.600726",
"sh.603936",
"sh.601218",
"sh.603387",
"sh.603757",
"sz.002487",
"sz.301449",
"sz.002667",
"sz.002056",
"sz.002150",
"sh.600746",
"sz.002463",
"sz.000890",
"sh.601139",
"sh.603803",
"sh.600367",
"sz.301667",
"sz.001207",
"sh.601016",
"sz.300677",
"sz.000990",
"sh.603175",
"sh.600844",
"sz.301165",
"sh.603248",
"sz.301099",
"sh.603949",
]
res_df_list=[]
for stock in tqdm.tqdm(stock_list):
    rs = bs.query_history_k_data_plus(stock,
        "date,time,code,open,high,low,close,volume,amount,adjustflag",
        start_date='2025-01-01', end_date='2026-03-22',
        frequency="5", adjustflag="3")
    # print('query_history_k_data_plus respond error_code:'+rs.error_code)
    # print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

    #### 打印结果集 ####
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())
    results = pd.DataFrame(data_list, columns=rs.fields)
    results['code']=stock
    res_df_list.append(results)
#### 结果集输出到csv文件 ####   
# result.to_csv("D:\\history_A_stock_k_data.csv", index=False)
# print(result)
result=pd.concat(res_df_list)
#### 登出系统 ####
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success

100%|██████████| 36/36 [11:17<00:00, 18.81s/it]

logout success!

In [233]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")
dtr=pd.read_sql("select code as code1,max(outstanding_share)  as ltgb from gp.stock where `date`>='2026-03-01' group by code",con=engine)

In [234]:
dtr['code2']=dtr['code1'].map(lambda x:x[0:2]+'.'+x[2:])

np.float64(33305838300.0)

In [221]:
result.index.size

460992

In [ ]:
df=result
# df['time']=df['time'].map(lambda x:x[:12])
df['time']=pd.to_datetime(df['time'],format="%Y%m%d%H%M%S%f")
df['hour']=df['time'].dt.hour
df['minute']=df['time'].dt.minute

df['pre_close']=df['close'].shift(1)
df=df.loc[df['date']!='2025-01-02']

res_df = []
for date, v in tqdm.tqdm(df.groupby(['code','date'])):
    # 1. 计算当天最高价 (这是标量，没问题)
    today_high = v['high'].max()
    # 2. 提取特定时间的数据，并强制转换为标量 (使用 .iloc[0])
    # 添加简单的错误处理，防止某天缺少开盘或收盘数据
    
    # 提取开盘 (09:35)
    open_series = v.loc[(v['hour']==9) & (v['minute']==35), 'open']
    if open_series.empty:
        continue # 或者设为 np.nan
    today_open = open_series.iloc[0]
    
    # 提取收盘 (15:00)
    close_series = v.loc[(v['hour']==15) & (v['minute']==0), 'close']
    if close_series.empty:
        continue
    today_close = close_series.iloc[0]
    
    # 提取昨收 (09:35 的 pre_close)
    yes_close_series = v.loc[(v['hour']==9) & (v['minute']==35), 'pre_close']
    if yes_close_series.empty:
        continue
    yes_close = yes_close_series.iloc[0]
    
    # 3. 确保是浮点数进行计算
    today_open = float(today_open)
    today_close = float(today_close)
    yes_close = float(yes_close)
    
    # 4. 计算涨幅 (此时都是数字，不会报错)
    # 防止除以0
    if yes_close != 0:
        zf = round((today_close - yes_close) / yes_close, 2)
    else:
        zf = 0.0
        
    if today_open != 0:
        sjzf = round((today_close - today_open) / today_open, 2)
    else:
        sjzf = 0.0
    
    # 5. 赋值给新列
    # 因为今天是标量 (scalar)，Pandas 会自动广播到该组的所有行
    v['today_high'] = today_high   # 修正了变量名拼写 hight -> high
    v['today_open'] = today_open
    v['today_close'] = today_close
    v['yes_close'] = yes_close
    v['zf'] = zf
    v['sjzf'] = sjzf
    v=v.iloc[0:3]
    res_df.append(v)

# 合并数据
if res_df:
    dfs = pd.concat(res_df, ignore_index=False) # 保持原有索引或重置
    print("处理完成，前5行数据：")
    print(dfs.head())
else:
    print("未生成任何数据，请检查时间筛选条件是否匹配。")

def estimate_bar_buy_ratio(row):
    high = row['high']
    low = row['low']
    close = row['close']
    
    # 处理可能的缺失值 (NaN)
    if pd.isna(high) or pd.isna(low) or pd.isna(close):
        return np.nan
    range_val = high - low
    # print(range_val)
    if range_val == 0:
        return 0.5 # 无波动视为中性
    
    ratio = (close - low) / range_val
    return round(ratio,2)

dfs['high']=dfs['high'].astype(float)
dfs['low']=dfs['low'].astype(float)
dfs['close']=dfs['close'].astype(float)
dfs['buy_ratio']=dfs.apply(estimate_bar_buy_ratio,axis=1)


dfs['volume']=dfs['volume'].astype(int)
dfs['est_buy_vol'] = dfs['volume'] * dfs['buy_ratio']
dfs['est_sell_vol'] = dfs['volume'] * (1 - dfs['buy_ratio'])

dfs=pd.merge(left=dfs,right=dtr,left_on='code',right_on='code2')



min15_df=[]
for k,v in dfs.groupby(['code','date']):
    buy_volume=v['est_buy_vol'].sum()
    sell_volume=v['est_sell_vol'].sum()
    # if sell_volume==0:
    #     buy_ratio=-1
    # else:
    #     buy_ratio=buy_volume/sell_volume

    buy_ratio=(buy_volume+1e-8)/(sell_volume+1e-8)
    if buy_ratio>50:
        buy_ratio=50
    all_volume=buy_volume+sell_volume
    all_lt_volume=v.loc[0,'ltgb']
    zb=round(all_volume/all_lt_volume,4)
    v.reset_index(drop=True,inplace=True)
    zf=v.loc[0,'zf']
    sjzf=v.loc[0,'sjzf']
    dt={
        "buy_volume":buy_volume,
        "sell_volume":sell_volume,
        "buy_ratio":buy_ratio,
        "all_volume":all_volume,
        "zb":zb,
        "zf":zf,
        "sjzf":sjzf,
        "date":k
    }
    min15_df.append(dt)
min15_df=pd.DataFrame(min15_df)
min15_df['next_day_zf']=min15_df['zf'].shift(-1)

 70%|██████▉   | 6661/9572 [00:13<00:06, 481.84it/s]

KeyboardInterrupt:

In [192]:
min_buy_ratio=min15_df['buy_ratio'].min()
max_buy_ratio=min15_df['buy_ratio'].max()

if max_buy_ratio - min_buy_ratio != 0:
    min15_df['buy_ratio_norm'] = (min15_df['buy_ratio'] - min_buy_ratio) / (max_buy_ratio - min_buy_ratio)
else:
    min15_df['buy_ratio_norm'] = 0.0 # 所有值相同，归一化为 0

In [193]:
bins = np.arange(0, 1.1, 0.1) # [0.0, 0.1, 0.2, ..., 1.0]
labels = [f"{i/10:.1f}-{(i+1)/10:.1f}" for i in range(10)] # ["0.0-0.1", "0.1-0.2", ..., "0.9-1.0"]

In [194]:
min15_df['ratio_group'] = pd.cut(min15_df['buy_ratio_norm'], bins=bins, labels=labels, right=False)

In [ ]:
min_zb=min15_df['zb'].min()
max_zb=min15_df['zb'].max()

if max_zb - min_zb != 0:
    min15_df['zb_norm'] = (min15_df['zb'] - min_zb) / (max_zb - min_zb)
else:
    min15_df['zb_norm'] = 0.0 # 所有值相同，归一化为 0
min15_df['zb_group'] = pd.cut(min15_df['zb_norm'], bins=bins, labels=labels, right=False)
min15_df['zf_and_next_sum'] = min15_df['zf'] + min15_df['next_day_zf']

In [204]:
func_pos_rate = lambda x: (x >= 0).sum() / x.count()
func_pos_rate.__name__ = 'win_rate'  # 设置别名为 win_rate

func_neg_count = lambda x: (x < 0).sum()
func_neg_count.__name__ = 'loss_count' # 设置别名

func_pos_count = lambda x: (x >= 0).sum()
func_pos_count.__name__ = 'win_ratio' # 设置别名

In [205]:
min15_df.groupby('ratio_group').agg({
    'zf': ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,
           ],
    'zf_and_next_sum':
        ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,]
}).reset_index()

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\2086780604.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min15_df.groupby('ratio_group').agg({
C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\90207440.py:1: RuntimeWarning: invalid value encountered in scalar divide
  func_pos_rate = lambda x: (x >= 0).sum() / x.count()

  ratio_group    zf                                                           \
              count      mean       std   sum win_ratio loss_count  win_rate
0     0.0-0.1   191 -0.001937  0.035421 -0.37        98         93  0.513089
1     0.1-0.2    54  0.004815  0.030576  0.26        36         18  0.666667
2     0.2-0.3    23  0.014783  0.025738  0.34        18          5  0.782609
3     0.3-0.4    13  0.022308  0.037893  0.29         9          4  0.692308
4     0.4-0.5     2  0.035000  0.007071  0.07         2          0  1.000000
5     0.5-0.6     3  0.010000  0.036056  0.03         2          1  0.666667
6     0.6-0.7     1  0.100000       NaN  0.10         1          0  1.000000
7     0.7-0.8     2  0.050000  0.070711  0.10         2          0  1.000000
8     0.8-0.9     1  0.100000       NaN  0.10         1          0  1.000000
9     0.9-1.0     0       NaN       NaN  0.00         0          0       NaN

  zf_and_next_sum
            count      mean       std   sum win_ratio loss_count  win_rate
0             190 -0.000158  0.050798 -0.03        97         93  0.510526
1              54  0.013704  0.046105  0.74        37         17  0.685185
2              23  0.012609  0.049472  0.29        14          9  0.608696
3              13  0.033077  0.062234  0.43         9          4  0.692308
4               2  0.085000  0.063640  0.17         2          0  1.000000
5               3  0.003333  0.060277  0.01         2          1  0.666667
6               1  0.120000       NaN  0.12         1          0  1.000000
7               2  0.095000  0.148492  0.19         1          1  0.500000
8               1  0.050000       NaN  0.05         1          0  1.000000
9               0       NaN       NaN  0.00         0          0       NaN

In [198]:
min15_df.loc[min15_df['buy_ratio_norm']>=0.7].agg({
    'zf':['count',
          lambda x:(x>0).sum()/x.count()],
    'zf_and_next_sum':[
        'count',
        lambda x:(x>0).sum()/x.count()],
    
})

            zf  zf_and_next_sum
count     4.00             4.00
<lambda>  0.75             0.75

In [206]:
min15_group=min15_df.groupby(['ratio_group','zb_group']).agg({
    'zf': ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,
           ],
    'zf_and_next_sum':
        ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,],
}).reset_index()

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\3062109942.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min15_group=min15_df.groupby(['ratio_group','zb_group']).agg({

In [209]:
min15_df.groupby('zb_group').agg({
    'zf': ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,
           ],
    'zf_and_next_sum':
        ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,]
}).reset_index()

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\817794629.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min15_df.groupby('zb_group').agg({
C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\90207440.py:1: RuntimeWarning: invalid value encountered in scalar divide
  func_pos_rate = lambda x: (x >= 0).sum() / x.count()

  zb_group    zf                                                           \
           count      mean       std   sum win_ratio loss_count  win_rate
0  0.0-0.1   205  0.000098  0.024495  0.02       120         85  0.585366
1  0.1-0.2    32  0.007812  0.041716  0.25        19         13  0.593750
2  0.2-0.3    23  0.000870  0.060521  0.02         9         14  0.391304
3  0.3-0.4    15  0.005333  0.063230  0.08         9          6  0.600000
4  0.4-0.5     6  0.035000  0.041833  0.21         5          1  0.833333
5  0.5-0.6     2 -0.005000  0.035355 -0.01         1          1  0.500000
6  0.6-0.7     3  0.076667  0.040415  0.23         3          0  1.000000
7  0.7-0.8     2 -0.010000  0.056569 -0.02         1          1  0.500000
8  0.8-0.9     2  0.070000  0.042426  0.14         2          0  1.000000
9  0.9-1.0     0       NaN       NaN  0.00         0          0       NaN

  zf_and_next_sum
            count      mean       std   sum win_ratio loss_count  win_rate
0             205  0.002585  0.039639  0.53       118         87  0.575610
1              32  0.015625  0.068342  0.50        18         14  0.562500
2              22  0.007273  0.089718  0.16         9         13  0.409091
3              15  0.012667  0.068292  0.19         9          6  0.600000
4               6  0.016667  0.070333  0.10         3          3  0.500000
5               2  0.010000  0.056569  0.02         1          1  0.500000
6               3  0.076667  0.070946  0.23         3          0  1.000000
7               2  0.050000  0.113137  0.10         1          1  0.500000
8               2  0.040000  0.014142  0.08         2          0  1.000000
9               0       NaN       NaN  0.00         0          0       NaN

In [207]:
min15_group.to_excel(r'C:\Users\cyw\Desktop\jupyternotebook\git-python\GP\当日策列\static\15min_group.xlsx')

In [115]:
min15_df.to_excel(r'C:\Users\cyw\Desktop\jupyternotebook\git-python\GP\当日策列\static\15mincnt.xlsx',index=False)

In [208]:
min15_df.head()

,buy_volume,sell_volume,buy_ratio,all_volume,zb,zf,sjzf,date,next_day_zf,buy_ratio_norm,ratio_group,zb_norm,zb_group,zf_and_next_sum
0,57666.0,82734.0,0.697005,140400.0,0.0001,-0.02,-0.02,2025-01-03,0.01,0.055716,0.0-0.1,0.006024,0.0-0.1,-0.01
1,36234.0,66366.0,0.545972,102600.0,0.0001,0.01,0.01,2025-01-06,0.03,0.043336,0.0-0.1,0.006024,0.0-0.1,0.04
2,89547.0,77953.0,1.148731,167500.0,0.0002,0.03,0.03,2025-01-07,0.00,0.092744,0.0-0.1,0.012048,0.0-0.1,0.03
3,59200.0,102600.0,0.576998,161800.0,0.0001,0.00,-0.00,2025-01-08,-0.04,0.045879,0.0-0.1,0.006024,0.0-0.1,-0.04
4,31226.0,196874.0,0.158609,228100.0,0.0002,-0.04,-0.04,2025-01-09,-0.02,0.011584,0.0-0.1,0.012048,0.0-0.1,-0.06

相关性分析

In [210]:
print("=== 相关性分析 ===")
print(min15_df[['buy_ratio_norm','zb_norm','zf','next_day_zf']].corr())

=== 相关性分析 ===
                buy_ratio_norm   zb_norm        zf  next_day_zf
buy_ratio_norm        1.000000  0.291130  0.363164     0.083800
zb_norm               0.291130  1.000000  0.231623     0.066744
zf                    0.363164  0.231623  1.000000     0.092585
next_day_zf           0.083800  0.066744  0.092585     1.000000

In [211]:
ratio_ret = min15_df.groupby('ratio_group')['zf'].mean()
print(ratio_ret)

ratio_group
0.0-0.1   -0.001937
0.1-0.2    0.004815
0.2-0.3    0.014783
0.3-0.4    0.022308
0.4-0.5    0.035000
0.5-0.6    0.010000
0.6-0.7    0.100000
0.7-0.8    0.050000
0.8-0.9    0.100000
0.9-1.0         NaN
Name: zf, dtype: float64

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\3692633278.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ratio_ret = min15_df.groupby('ratio_group')['zf'].mean()

In [212]:
zb_ret = min15_df.groupby('zb_group')['zf'].mean()

print(zb_ret)

zb_group
0.0-0.1    0.000098
0.1-0.2    0.007812
0.2-0.3    0.000870
0.3-0.4    0.005333
0.4-0.5    0.035000
0.5-0.6   -0.005000
0.6-0.7    0.076667
0.7-0.8   -0.010000
0.8-0.9    0.070000
0.9-1.0         NaN
Name: zf, dtype: float64

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\2155074054.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  zb_ret = min15_df.groupby('zb_group')['zf'].mean()

In [ ]:
min15_df['alpha'] = (
    0.6 * min15_df['buy_ratio_norm'] + 
    0.4 * min15_df['zb_norm']
)
alpha_ret = min15_df.groupby(pd.cut(min15_df['alpha'], bins=bins))['zf'].mean()
print(alpha_ret)

alpha
(0.0, 0.1]   -0.001868
(0.1, 0.2]    0.001791
(0.2, 0.3]    0.020000
(0.3, 0.4]    0.025000
(0.4, 0.5]    0.007500
(0.5, 0.6]    0.074000
(0.6, 0.7]         NaN
(0.7, 0.8]         NaN
(0.8, 0.9]    0.100000
(0.9, 1.0]         NaN
Name: zf, dtype: float64

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\4270486251.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  alpha_ret = min15_df.groupby(pd.cut(min15_df['alpha'], bins=bins))['zf'].mean()