In [1]:
import logging

import numpy as np
import pandas as pd
import akshare as ak

import warnings
warnings.filterwarnings("ignore", category=UserWarning)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

In [2]:
df = ak.stock_zh_a_tick_tx_js(symbol='sz002487')

In [14]:
df.to_excel('1.xlsx')

In [3]:
df.head()

       成交时间   成交价格  价格变动   成交量     成交金额  性质
0  09:25:00  70.36  0.46  1315  9252340  买盘
1  09:30:00  70.50  0.14   834  5871373  买盘
2  09:30:03  70.48 -0.02   374  2638263  卖盘
3  09:30:06  70.42 -0.06   652  4590780  卖盘
4  09:30:09  70.37 -0.05   264  1858127  卖盘

In [22]:
# ===== 1️⃣ 转时间格式 =====
df["成交时间"] = pd.to_datetime(df["成交时间"])

# ===== 2️⃣ 提取分钟 =====
df["分钟"] = df["成交时间"].dt.floor("min")

# ===== 3️⃣ 标记买卖 =====
df["买量"] = df.apply(lambda x: x["成交量"] if x["性质"] == "买盘" or (x["性质"]=="中性盘" and x["价格变动"]>0) else 0, axis=1)

df["卖量"] = df.apply(lambda x: x["成交量"] if x["性质"] == "卖盘" or (x["性质"]=="中性盘" and x["价格变动"]<0) else 0, axis=1)

# ===== 4️⃣ 按分钟聚合 =====
minute_df = df.groupby("分钟").agg({
    "买量": "sum",
    "卖量": "sum",
    "成交量": "sum"
}).reset_index()

# ===== 5️⃣ 计算买卖比 =====
minute_df["买卖比"] = minute_df["买量"] / (minute_df["卖量"] + 1e-6)
minute_df["买卖差"] = minute_df["买量"] - minute_df["卖量"]
minute_df["买卖比"] = minute_df["买卖比"].round(2)
minute_df["买卖比"] = minute_df["买卖比"].map(lambda x: f"{x:.2f}")
print(minute_df)

                     分钟    买量    卖量   成交量            买卖比   买卖差
0   2026-03-22 09:25:00  1315     0  1315  1315000000.00  1315
1   2026-03-22 09:30:00  3166  3218  6569           0.98   -52
2   2026-03-22 09:31:00  2424   774  3198           3.13  1650
3   2026-03-22 09:32:00  1556  1435  2991           1.08   121
4   2026-03-22 09:33:00  1069  1728  2797           0.62  -659
..                  ...   ...   ...   ...            ...   ...
236 2026-03-22 14:54:00   388  1050  1438           0.37  -662
237 2026-03-22 14:55:00  1304   916  2220           1.42   388
238 2026-03-22 14:56:00  1184  1671  2855           0.71  -487
239 2026-03-22 14:57:00    58     0    58    58000000.00    58
240 2026-03-22 15:00:00     0  3583  3583           0.00 -3583

[241 rows x 6 columns]

In [23]:
minute_df["order_flow"] = (
    minute_df["买量"] - minute_df["卖量"]
) / (minute_df["成交量"] + 1e-6)

In [24]:
minute_df["买占比"] = minute_df["买量"] / (minute_df["成交量"] + 1e-6)

In [25]:
minute_df.head(20)

,分钟,买量,卖量,成交量,买卖比,买卖差,order_flow,买占比
0,2026-03-22 09:25:00,1315,0,1315,1315000000.00,1315,1.000000,1.000000
1,2026-03-22 09:30:00,3166,3218,6569,0.98,-52,-0.007916,0.481961
2,2026-03-22 09:31:00,2424,774,3198,3.13,1650,0.515947,0.757974
3,2026-03-22 09:32:00,1556,1435,2991,1.08,121,0.040455,0.520227
4,2026-03-22 09:33:00,1069,1728,2797,0.62,-659,-0.235610,0.382195
5,2026-03-22 09:34:00,323,2004,2327,0.16,-1681,-0.722389,0.138805
6,2026-03-22 09:35:00,1579,1169,2774,1.35,410,0.147801,0.569214
7,2026-03-22 09:36:00,2207,654,2861,3.37,1553,0.542817,0.771409
8,2026-03-22 09:37:00,5116,1384,6500,3.70,3732,0.574154,0.787077
9,2026-03-22 09:38:00,2344,2155,4499,1.09,189,0.042009,0.521005
10,2026-03-22 09:39:00,3878,1598,5476,2.43,2280,0.416362,0.708181
11,2026-03-22 09:40:00,1619,2420,4039,0.67,-801,-0.198316,0.400842
12,2026-03-22 09:41:00,3692,1669,5361,2.21,2023,0.377355,0.688677
13,2026-03-22 09:42:00,2393,1365,3758,1.75,1028,0.273550,0.636775
14,2026-03-22 09:43:00,1439,1451,2890,0.99,-12,-0.004152,0.497924
15,2026-03-22 09:44:00,3903,1033,4936,3.78,2870,0.581442,0.790721
16,2026-03-22 09:45:00,3189,2419,5867,1.32,770,0.131243,0.543549
17,2026-03-22 09:46:00,1089,2016,3105,0.54,-927,-0.298551,0.350725
18,2026-03-22 09:47:00,562,1337,1899,0.42,-775,-0.408110,0.295945
19,2026-03-22 09:48:00,1057,2353,3410,0.45,-1296,-0.380059,0.309971

In [28]:
df["累计成交额"] = df["成交金额"].cumsum()
df["累计成交量"] = df["成交量"].cumsum()*100
df["VWAP"] = df["累计成交额"] / df["累计成交量"]

In [30]:
df.head(20)

,成交时间,成交价格,价格变动,成交量,成交金额,性质,分钟,买量,卖量,累计成交额,累计成交量,VWAP
0,2026-03-22 09:25:00,70.36,0.46,1315,9252340,买盘,2026-03-22 09:25:00,1315,0,9252340,131500,70.360000
1,2026-03-22 09:30:00,70.50,0.14,834,5871373,买盘,2026-03-22 09:30:00,834,0,15123713,214900,70.375584
2,2026-03-22 09:30:03,70.48,-0.02,374,2638263,卖盘,2026-03-22 09:30:00,0,374,17761976,252300,70.400222
3,2026-03-22 09:30:06,70.42,-0.06,652,4590780,卖盘,2026-03-22 09:30:00,0,652,22352756,317500,70.402381
4,2026-03-22 09:30:09,70.37,-0.05,264,1858127,卖盘,2026-03-22 09:30:00,0,264,24210883,343900,70.400939
5,2026-03-22 09:30:12,70.36,-0.01,518,3645070,卖盘,2026-03-22 09:30:00,0,518,27855953,395700,70.396646
6,2026-03-22 09:30:15,70.32,-0.04,185,1301441,卖盘,2026-03-22 09:30:00,0,185,29157394,414200,70.394481
7,2026-03-22 09:30:18,70.25,-0.07,80,562356,卖盘,2026-03-22 09:30:00,0,80,29719750,422200,70.392586
8,2026-03-22 09:30:21,70.13,-0.12,65,456086,卖盘,2026-03-22 09:30:00,0,65,30175836,428700,70.389167
9,2026-03-22 09:30:24,70.00,-0.13,151,1057270,卖盘,2026-03-22 09:30:00,0,151,31233106,443800,70.376534
10,2026-03-22 09:30:27,69.88,-0.12,53,370587,卖盘,2026-03-22 09:30:00,0,53,31603693,449100,70.371171
11,2026-03-22 09:30:30,69.88,0.00,301,2103432,卖盘,2026-03-22 09:30:00,0,301,33707125,479200,70.340411
12,2026-03-22 09:30:33,69.80,-0.08,78,544576,卖盘,2026-03-22 09:30:00,0,78,34251701,487000,70.332035
13,2026-03-22 09:30:36,69.61,-0.19,312,2176966,卖盘,2026-03-22 09:30:00,0,312,36428667,518200,70.298470
14,2026-03-22 09:30:39,69.60,-0.01,185,1287968,卖盘,2026-03-22 09:30:00,0,185,37716635,536700,70.275079
15,2026-03-22 09:30:42,69.61,0.01,597,4155021,买盘,2026-03-22 09:30:00,597,0,41871656,596400,70.207337
16,2026-03-22 09:30:45,69.81,0.20,791,5517315,买盘,2026-03-22 09:30:00,791,0,47388971,675500,70.153917
17,2026-03-22 09:30:48,70.00,0.19,465,3246744,买盘,2026-03-22 09:30:00,465,0,50635715,722000,70.132569
18,2026-03-22 09:30:51,70.11,0.11,97,679067,买盘,2026-03-22 09:30:00,97,0,51314782,731700,70.130903
19,2026-03-22 09:30:54,70.36,0.25,382,2682684,买盘,2026-03-22 09:30:00,382,0,53997466,769900,70.135688

In [31]:
df["VWAP斜率"] = df["VWAP"].diff()
df["均价抬高"] = df["VWAP斜率"] > 0

In [32]:
df.head(20)

,成交时间,成交价格,价格变动,成交量,成交金额,性质,分钟,买量,卖量,累计成交额,累计成交量,VWAP,VWAP斜率,均价抬高
0,2026-03-22 09:25:00,70.36,0.46,1315,9252340,买盘,2026-03-22 09:25:00,1315,0,9252340,131500,70.360000,NaN,False
1,2026-03-22 09:30:00,70.50,0.14,834,5871373,买盘,2026-03-22 09:30:00,834,0,15123713,214900,70.375584,0.015584,True
2,2026-03-22 09:30:03,70.48,-0.02,374,2638263,卖盘,2026-03-22 09:30:00,0,374,17761976,252300,70.400222,0.024638,True
3,2026-03-22 09:30:06,70.42,-0.06,652,4590780,卖盘,2026-03-22 09:30:00,0,652,22352756,317500,70.402381,0.002159,True
4,2026-03-22 09:30:09,70.37,-0.05,264,1858127,卖盘,2026-03-22 09:30:00,0,264,24210883,343900,70.400939,-0.001442,False
5,2026-03-22 09:30:12,70.36,-0.01,518,3645070,卖盘,2026-03-22 09:30:00,0,518,27855953,395700,70.396646,-0.004293,False
6,2026-03-22 09:30:15,70.32,-0.04,185,1301441,卖盘,2026-03-22 09:30:00,0,185,29157394,414200,70.394481,-0.002166,False
7,2026-03-22 09:30:18,70.25,-0.07,80,562356,卖盘,2026-03-22 09:30:00,0,80,29719750,422200,70.392586,-0.001894,False
8,2026-03-22 09:30:21,70.13,-0.12,65,456086,卖盘,2026-03-22 09:30:00,0,65,30175836,428700,70.389167,-0.003419,False
9,2026-03-22 09:30:24,70.00,-0.13,151,1057270,卖盘,2026-03-22 09:30:00,0,151,31233106,443800,70.376534,-0.012633,False
10,2026-03-22 09:30:27,69.88,-0.12,53,370587,卖盘,2026-03-22 09:30:00,0,53,31603693,449100,70.371171,-0.005363,False
11,2026-03-22 09:30:30,69.88,0.00,301,2103432,卖盘,2026-03-22 09:30:00,0,301,33707125,479200,70.340411,-0.030760,False
12,2026-03-22 09:30:33,69.80,-0.08,78,544576,卖盘,2026-03-22 09:30:00,0,78,34251701,487000,70.332035,-0.008376,False
13,2026-03-22 09:30:36,69.61,-0.19,312,2176966,卖盘,2026-03-22 09:30:00,0,312,36428667,518200,70.298470,-0.033565,False
14,2026-03-22 09:30:39,69.60,-0.01,185,1287968,卖盘,2026-03-22 09:30:00,0,185,37716635,536700,70.275079,-0.023391,False
15,2026-03-22 09:30:42,69.61,0.01,597,4155021,买盘,2026-03-22 09:30:00,597,0,41871656,596400,70.207337,-0.067742,False
16,2026-03-22 09:30:45,69.81,0.20,791,5517315,买盘,2026-03-22 09:30:00,791,0,47388971,675500,70.153917,-0.053420,False
17,2026-03-22 09:30:48,70.00,0.19,465,3246744,买盘,2026-03-22 09:30:00,465,0,50635715,722000,70.132569,-0.021348,False
18,2026-03-22 09:30:51,70.11,0.11,97,679067,买盘,2026-03-22 09:30:00,97,0,51314782,731700,70.130903,-0.001666,False
19,2026-03-22 09:30:54,70.36,0.25,382,2682684,买盘,2026-03-22 09:30:00,382,0,53997466,769900,70.135688,0.004784,True

In [306]:

import baostock as bs
import pandas as pd
import tqdm
#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

#### 获取沪深A股历史K线数据 ####
# 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
# 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
# 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
stock_list=[
"sh.600370",
"sz.002310",
"sh.601669"]
res_df_list=[]
for stock in tqdm.tqdm(stock_list):
    rs = bs.query_history_k_data_plus(stock,
        "date,time,code,open,high,low,close,volume,amount,adjustflag",
        start_date='2025-01-01', end_date='2026-03-22',
        frequency="5", adjustflag="3")
    # print('query_history_k_data_plus respond error_code:'+rs.error_code)
    # print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

    #### 打印结果集 ####
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())
    results = pd.DataFrame(data_list, columns=rs.fields)
    results['code']=stock
    res_df_list.append(results)
#### 结果集输出到csv文件 ####   
# result.to_csv("D:\\history_A_stock_k_data.csv", index=False)
# print(result)
result=pd.concat(res_df_list)
#### 登出系统 ####
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success

100%|██████████| 3/3 [00:58<00:00, 19.33s/it]

logout success!

In [307]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:chen@127.0.0.1:3306/gp")
dtr=pd.read_sql("select code as code1,max(outstanding_share)  as ltgb from gp.stock where `date`>='2026-03-01' group by code",con=engine)

In [308]:
dtr['code2']=dtr['code1'].map(lambda x:x[0:2]+'.'+x[2:])

In [309]:
result.index.size

42000

In [310]:
df=result
# df['time']=df['time'].map(lambda x:x[:12])
df['time']=pd.to_datetime(df['time'],format="%Y%m%d%H%M%S%f")
df['hour']=df['time'].dt.hour
df['minute']=df['time'].dt.minute

df['pre_close']=df['close'].shift(1)
df=df.loc[df['date']!='2025-01-02']

res_df = []
for date, v in tqdm.tqdm(df.groupby(['code','date'])):
    # 1. 计算当天最高价 (这是标量，没问题)
    today_high = v['high'].max()
    # 2. 提取特定时间的数据，并强制转换为标量 (使用 .iloc[0])
    # 添加简单的错误处理，防止某天缺少开盘或收盘数据
    
    # 提取开盘 (09:35)
    open_series = v.loc[(v['hour']==9) & (v['minute']==35), 'open']
    if open_series.empty:
        continue # 或者设为 np.nan
    today_open = open_series.iloc[0]
    
    # 提取收盘 (15:00)
    close_series = v.loc[(v['hour']==15) & (v['minute']==0), 'close']
    if close_series.empty:
        continue
    today_close = close_series.iloc[0]
    
    # 提取昨收 (09:35 的 pre_close)
    yes_close_series = v.loc[(v['hour']==9) & (v['minute']==35), 'pre_close']
    if yes_close_series.empty:
        continue
    yes_close = yes_close_series.iloc[0]
    
    # 3. 确保是浮点数进行计算
    today_open = float(today_open)
    today_close = float(today_close)
    yes_close = float(yes_close)
    
    # 4. 计算涨幅 (此时都是数字，不会报错)
    # 防止除以0
    if yes_close != 0:
        zf = round((today_close - yes_close) / yes_close, 2)
    else:
        zf = 0.0
        
    if today_open != 0:
        sjzf = round((today_close - today_open) / today_open, 2)
    else:
        sjzf = 0.0
    
    # 5. 赋值给新列
    # 因为今天是标量 (scalar)，Pandas 会自动广播到该组的所有行
    v['today_high'] = today_high   # 修正了变量名拼写 hight -> high
    v['today_open'] = today_open
    v['today_close'] = today_close
    v['yes_close'] = yes_close
    v['zf'] = zf
    v['sjzf'] = sjzf
    v=v.iloc[0:3]
    res_df.append(v)

# 合并数据
if res_df:
    dfs = pd.concat(res_df, ignore_index=False) # 保持原有索引或重置
    print("处理完成，前5行数据：")
    # print(dfs.head())
else:
    print("未生成任何数据，请检查时间筛选条件是否匹配。")

def estimate_bar_buy_ratio(row):
    high = row['high']
    low = row['low']
    close = row['close']
    
    # 处理可能的缺失值 (NaN)
    if pd.isna(high) or pd.isna(low) or pd.isna(close):
        return np.nan
    range_val = high - low
    # print(range_val)
    if range_val == 0:
        return 0.5 # 无波动视为中性
    
    ratio = (close - low) / range_val
    return round(ratio,2)

dfs['high']=dfs['high'].astype(float)
dfs['low']=dfs['low'].astype(float)
dfs['close']=dfs['close'].astype(float)
dfs['buy_ratio']=dfs.apply(estimate_bar_buy_ratio,axis=1)


dfs['volume']=dfs['volume'].astype(int)
dfs['est_buy_vol'] = dfs['volume'] * dfs['buy_ratio']
dfs['est_sell_vol'] = dfs['volume'] * (1 - dfs['buy_ratio'])

dfs=pd.merge(left=dfs,right=dtr,left_on='code',right_on='code2')



min15_df=[]
for k,v in dfs.groupby(['code','date']):
    buy_volume=v['est_buy_vol'].sum()
    sell_volume=v['est_sell_vol'].sum()
    # if sell_volume==0:
    #     buy_ratio=-1
    # else:
    #     buy_ratio=buy_volume/sell_volume

    buy_ratio=(buy_volume+1e-8)/(sell_volume+1e-8)
    if sell_volume==0 or buy_volume==0:
        continue
    all_volume=buy_volume+sell_volume
    all_lt_volume=v.iloc[0]['ltgb']
    zb=round(all_volume/all_lt_volume,4)
    v.reset_index(drop=True,inplace=True)
    zf=v.loc[0,'zf']
    sjzf=v.loc[0,'sjzf']
    dt={
        "buy_volume":buy_volume,
        "sell_volume":sell_volume,
        "buy_ratio":buy_ratio,
        "all_volume":all_volume,
        "zb":zb,
        "zf":zf,
        "sjzf":sjzf,
        "date":k[1],
        'code':k[0]
    }
    min15_df.append(dt)
min15_df=pd.DataFrame(min15_df)
min15_df['next_day_zf']=min15_df['zf'].shift(-1)

100%|██████████| 872/872 [00:01<00:00, 507.77it/s]

处理完成，前5行数据：

In [311]:

min15_df_ls=[]
for k,v in tqdm.tqdm(min15_df.groupby('code')):
    min_buy_ratio=v['buy_ratio'].min()
    max_buy_ratio=v['buy_ratio'].max()
    
    if max_buy_ratio - min_buy_ratio != 0:
        v['buy_ratio_norm'] = (v['buy_ratio'] - min_buy_ratio) / (max_buy_ratio - min_buy_ratio)
    else:
        v['buy_ratio_norm'] = 0.0 # 所有值相同，归一化为 0
    bins = np.arange(0, 1.1, 0.1) # [0.0, 0.1, 0.2, ..., 1.0]
    labels = [f"{i/10:.1f}-{(i+1)/10:.1f}" for i in range(10)] # ["0.0-0.1", "0.1-0.2", ..., "0.9-1.0"]
    v['ratio_group'] = pd.cut(v['buy_ratio_norm'], bins=bins, labels=labels, right=False)
    min_zb=v['zb'].min()
    max_zb=v['zb'].max()
    
    if max_zb - min_zb != 0:
        v['zb_norm'] = (v['zb'] - min_zb) / (max_zb - min_zb)
    else:
        v['zb_norm'] = 0.0 # 所有值相同，归一化为 0
    v['zb_group'] = pd.cut(v['zb_norm'], bins=bins, labels=labels, right=False)
    v['zf_and_next_sum'] = v['zf'] + v['next_day_zf']
    min15_df_ls.append(v)
min15_all_df=pd.concat(min15_df_ls)

100%|██████████| 3/3 [00:00<00:00, 230.63it/s]

In [312]:
min15_all_df

,buy_volume,sell_volume,buy_ratio,all_volume,zb,zf,sjzf,date,code,next_day_zf,buy_ratio_norm,ratio_group,zb_norm,zb_group,zf_and_next_sum
0,1.717532e+06,1.186568e+06,1.447479,2904100.0,0.0007,-0.04,-0.04,2025-01-03,sh.600370,-0.01,0.052654,0.0-0.1,0.006421,0.0-0.1,-0.05
1,1.509940e+06,1.933560e+06,0.780912,3443500.0,0.0009,-0.01,0.00,2025-01-06,sh.600370,0.03,0.028045,0.0-0.1,0.009631,0.0-0.1,0.02
2,1.227330e+06,8.400700e+05,1.460985,2067400.0,0.0005,0.03,0.03,2025-01-07,sh.600370,0.00,0.053153,0.0-0.1,0.003210,0.0-0.1,0.03
3,5.193500e+05,1.072850e+06,0.484084,1592200.0,0.0004,0.00,0.01,2025-01-08,sh.600370,-0.01,0.017087,0.0-0.1,0.001605,0.0-0.1,-0.01
4,1.174381e+06,4.862190e+05,2.415333,1660600.0,0.0004,-0.01,0.02,2025-01-09,sh.600370,-0.05,0.088386,0.0-0.1,0.001605,0.0-0.1,-0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,1.681448e+08,3.497000e+06,48.082593,171641827.0,0.0409,0.10,0.10,2026-03-16,sz.002310,0.00,0.771430,0.7-0.8,0.552957,0.5-0.6,0.10
829,4.986860e+07,1.234587e+08,0.403929,173327280.0,0.0413,0.00,0.05,2026-03-17,sz.002310,-0.04,0.005430,0.0-0.1,0.558459,0.5-0.6,-0.04
830,6.936599e+07,3.318982e+07,2.089978,102555809.0,0.0244,-0.04,-0.03,2026-03-18,sz.002310,0.10,0.032518,0.0-0.1,0.325997,0.3-0.4,0.06
831,4.441555e+07,3.818036e+07,1.163309,82595915.0,0.0197,0.10,0.12,2026-03-19,sz.002310,0.10,0.017631,0.0-0.1,0.261348,0.2-0.3,0.20
832,3.028855e+08,5.143975e+06,58.881597,308029438.0,0.0734,0.10,0.07,2026-03-20,sz.002310,NaN,0.944925,0.9-1.0,1.000000,NaN,NaN

In [313]:
func_pos_rate = lambda x: (x >= 0).sum() / x.count()
func_pos_rate.__name__ = 'win_rate'  # 设置别名为 win_rate

func_neg_count = lambda x: (x < 0).sum()
func_neg_count.__name__ = 'loss_count' # 设置别名

func_pos_count = lambda x: (x >= 0).sum()
func_pos_count.__name__ = 'win_ratio' # 设置别名

In [314]:
min15_all_df.groupby('ratio_group').agg({
    'zf': ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,
           ],
    'zf_and_next_sum':
        ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,]
}).reset_index()

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\1125234901.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min15_all_df.groupby('ratio_group').agg({
C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\90207440.py:1: RuntimeWarning: invalid value encountered in scalar divide
  func_pos_rate = lambda x: (x >= 0).sum() / x.count()

  ratio_group    zf                                                           \
              count      mean       std   sum win_ratio loss_count  win_rate
0     0.0-0.1   657 -0.001065  0.027709 -0.70       384        273  0.584475
1     0.1-0.2   105  0.009238  0.028172  0.97        78         27  0.742857
2     0.2-0.3    25  0.017200  0.033232  0.43        23          2  0.920000
3     0.3-0.4    16  0.013125  0.010145  0.21        16          0  1.000000
4     0.4-0.5    10  0.006000  0.022706  0.06         8          2  0.800000
5     0.5-0.6    10  0.028000  0.044672  0.28         7          3  0.700000
6     0.6-0.7     0       NaN       NaN  0.00         0          0       NaN
7     0.7-0.8     5  0.044000  0.051284  0.22         5          0  1.000000
8     0.8-0.9     1  0.000000       NaN  0.00         1          0  1.000000
9     0.9-1.0     1  0.100000       NaN  0.10         1          0  1.000000

  zf_and_next_sum
            count      mean       std   sum win_ratio loss_count  win_rate
0             657  0.001096  0.042491  0.72       366        291  0.557078
1             105  0.010095  0.039088  1.06        70         35  0.666667
2              25  0.024000  0.062915  0.60        20          5  0.800000
3              16  0.013750  0.044253  0.22        12          4  0.750000
4              10  0.019000  0.044833  0.19         6          4  0.600000
5              10  0.019000  0.062263  0.19         6          4  0.600000
6               0       NaN       NaN  0.00         0          0       NaN
7               5  0.068000  0.083487  0.34         5          0  1.000000
8               1  0.000000       NaN  0.00         1          0  1.000000
9               0       NaN       NaN  0.00         0          0       NaN

In [316]:
min15_all_df.groupby('zb_group').agg({
    'zf': ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,
           ],
    'zf_and_next_sum':
        ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,]
}).reset_index()

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\1349297810.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min15_all_df.groupby('zb_group').agg({

  zb_group    zf                                                           \
           count      mean       std   sum win_ratio loss_count  win_rate
0  0.0-0.1   736  0.000122  0.022146  0.09       467        269  0.634511
1  0.1-0.2    48  0.003542  0.047913  0.17        24         24  0.500000
2  0.2-0.3    25  0.030800  0.055821  0.77        19          6  0.760000
3  0.3-0.4     8  0.025000  0.059522  0.20         5          3  0.625000
4  0.4-0.5     3 -0.026667  0.070238 -0.08         1          2  0.333333
5  0.5-0.6     5  0.066000  0.047749  0.33         5          0  1.000000
6  0.6-0.7     2 -0.065000  0.049497 -0.13         0          2  0.000000
7  0.7-0.8     1  0.100000       NaN  0.10         1          0  1.000000
8  0.8-0.9     1  0.100000       NaN  0.10         1          0  1.000000
9  0.9-1.0     1  0.100000       NaN  0.10         1          0  1.000000

  zf_and_next_sum
            count      mean       std   sum win_ratio loss_count  win_rate
0             736  0.002364  0.035126  1.74       434        302  0.589674
1              48  0.003958  0.077260  0.19        25         23  0.520833
2              25  0.034400  0.068804  0.86        15         10  0.600000
3               8  0.060000  0.073679  0.48         7          1  0.875000
4               3 -0.070000  0.072111 -0.21         0          3  0.000000
5               5  0.096000  0.107145  0.48         4          1  0.800000
6               2 -0.085000  0.035355 -0.17         0          2  0.000000
7               1  0.000000       NaN  0.00         1          0  1.000000
8               1  0.200000       NaN  0.20         1          0  1.000000
9               1  0.010000       NaN  0.01         1          0  1.000000

In [321]:
min15_all_df.loc[min15_all_df['buy_ratio_norm']>=0.2].agg({
    'zf':['count',
          lambda x:(x>0).sum()/x.count()],
    'zf_and_next_sum':[
        'count',
        lambda x:(x>0).sum()/x.count()],
    
})

                 zf  zf_and_next_sum
count     71.000000        70.000000
<lambda>   0.633803         0.614286

In [290]:
min15_all_group=min15_all_group.groupby(['ratio_group','zb_group']).agg({
    'zf': ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,
           ],
    'zf_and_next_sum':
        ['count', 
           'mean', 
           'std',
           'sum',
           func_pos_count,
           func_neg_count,
           func_pos_rate,],
}).reset_index()

NameError: name 'min15_all_group' is not defined

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\1349297810.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min15_all_df.groupby('zb_group').agg({

  zb_group    zf                                                           \
           count      mean       std   sum win_ratio loss_count  win_rate
0  0.0-0.1  6966  0.000504  0.020929  3.51      4521       2445  0.649009
1  0.1-0.2  1264  0.001313  0.038181  1.66       707        557  0.559335
2  0.2-0.3   533  0.002683  0.046616  1.43       290        243  0.544090
3  0.3-0.4   300  0.012733  0.049281  3.82       198        102  0.660000
4  0.4-0.5   177  0.009831  0.061009  1.74       109         68  0.615819
5  0.5-0.6   114  0.018333  0.079031  2.09        71         43  0.622807
6  0.6-0.7    79  0.017722  0.067291  1.40        49         30  0.620253
7  0.7-0.8    49  0.028980  0.068473  1.42        33         16  0.673469
8  0.8-0.9    27  0.065556  0.053084  1.77        24          3  0.888889
9  0.9-1.0    27  0.051111  0.139238  1.38        24          3  0.888889

  zf_and_next_sum
            count      mean       std    sum win_ratio loss_count  win_rate
0            6966  0.002682  0.033654  18.68      4272       2694  0.613264
1            1264  0.008782  0.120391  11.10       713        551  0.564082
2             533  0.022871  0.355738  12.19       295        238  0.553471
3             300  0.014067  0.071324   4.22       191        109  0.636667
4             176  0.008068  0.082585   1.42        99         77  0.562500
5             114  0.020263  0.100340   2.31        66         48  0.578947
6              79  0.017215  0.089097   1.36        47         32  0.594937
7              49  0.023673  0.098736   1.16        31         18  0.632653
8              27  0.070000  0.079227   1.89        23          4  0.851852
9              27  0.034074  0.205487   0.92        23          4  0.851852

In [ ]:
min15_group.to_excel(r'C:\Users\cyw\Desktop\jupyternotebook\git-python\GP\当日策列\static\15min_group.xlsx')

In [ ]:
min15_df.to_excel(r'C:\Users\cyw\Desktop\jupyternotebook\git-python\GP\当日策列\static\15mincnt.xlsx',index=False)

In [ ]:
min15_df.head()

,buy_volume,sell_volume,buy_ratio,all_volume,zb,zf,sjzf,date,next_day_zf,buy_ratio_norm,ratio_group,zb_norm,zb_group,zf_and_next_sum
0,57666.0,82734.0,0.697005,140400.0,0.0001,-0.02,-0.02,2025-01-03,0.01,0.055716,0.0-0.1,0.006024,0.0-0.1,-0.01
1,36234.0,66366.0,0.545972,102600.0,0.0001,0.01,0.01,2025-01-06,0.03,0.043336,0.0-0.1,0.006024,0.0-0.1,0.04
2,89547.0,77953.0,1.148731,167500.0,0.0002,0.03,0.03,2025-01-07,0.00,0.092744,0.0-0.1,0.012048,0.0-0.1,0.03
3,59200.0,102600.0,0.576998,161800.0,0.0001,0.00,-0.00,2025-01-08,-0.04,0.045879,0.0-0.1,0.006024,0.0-0.1,-0.04
4,31226.0,196874.0,0.158609,228100.0,0.0002,-0.04,-0.04,2025-01-09,-0.02,0.011584,0.0-0.1,0.012048,0.0-0.1,-0.06

相关性分析

In [ ]:
print("=== 相关性分析 ===")
print(min15_all_df[['buy_ratio_norm','zb_norm','zf','next_day_zf']].corr())

=== 相关性分析 ===
                buy_ratio_norm   zb_norm        zf  next_day_zf
buy_ratio_norm        1.000000  0.135154  0.078235     0.013830
zb_norm               0.135154  1.000000  0.133417    -0.002899
zf                    0.078235  0.133417  1.000000    -0.015595
next_day_zf           0.013830 -0.002899 -0.015595     1.000000

In [ ]:
ratio_ret = min15_all_df.groupby('ratio_group')['zf'].mean()
print(ratio_ret)

ratio_group
0.0-0.1    0.001054
0.1-0.2    0.020911
0.2-0.3    0.022828
0.3-0.4    0.032295
0.4-0.5    0.018966
0.5-0.6    0.041111
0.6-0.7    0.058462
0.7-0.8    0.047500
0.8-0.9    0.112500
0.9-1.0    0.082000
Name: zf, dtype: float64

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\352238637.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ratio_ret = min15_all_df.groupby('ratio_group')['zf'].mean()

In [ ]:
zb_ret = min15_all_df.groupby('zb_group')['zf'].mean()

print(zb_ret)

zb_group
0.0-0.1    0.000504
0.1-0.2    0.001313
0.2-0.3    0.002683
0.3-0.4    0.012733
0.4-0.5    0.009831
0.5-0.6    0.018333
0.6-0.7    0.017722
0.7-0.8    0.028980
0.8-0.9    0.065556
0.9-1.0    0.051111
Name: zf, dtype: float64

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\1011178616.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  zb_ret = min15_all_df.groupby('zb_group')['zf'].mean()

In [ ]:
min15_all_df['alpha'] = (
    0.6 * min15_all_df['buy_ratio_norm'] + 
    0.4 * min15_all_df['zb_norm']
)
alpha_ret = min15_all_df.groupby(pd.cut(min15_all_df['alpha'], bins=bins))['zf'].mean()
print(alpha_ret)

alpha
(0.0, 0.1]   -0.000629
(0.1, 0.2]    0.006169
(0.2, 0.3]    0.014958
(0.3, 0.4]    0.037907
(0.4, 0.5]    0.142759
(0.5, 0.6]    0.197692
(0.6, 0.7]    0.014286
(0.7, 0.8]    0.086923
(0.8, 0.9]    0.105385
(0.9, 1.0]    0.108000
Name: zf, dtype: float64

C:\Users\cyw\AppData\Local\Temp\ipykernel_29844\257292345.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  alpha_ret = min15_all_df.groupby(pd.cut(min15_all_df['alpha'], bins=bins))['zf'].mean()